version: '3'
services:
  quiz:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - MAX_PORT_ATTEMPTS=10
    volumes:
      - ./questions:/app/questions
